name: shuhang_mall_flutter
description: "数航商道 - Flutter 电商应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # 状态管理
  get: ^4.7.3

  # 网络请求
  dio: ^5.9.1

  # 本地存储
  shared_preferences: ^2.5.4

  # 图片加载缓存
  cached_network_image: ^3.4.1

  # 轮播图
  carousel_slider: ^5.1.1

  # 下拉刷新/上拉加载
  easy_refresh: ^3.4.0

  # 二维码生成
  qr_flutter: ^4.1.0

  # WebSocket
  web_socket_channel: ^3.0.3

  # 图片选择
  image_picker: ^1.2.1

  # 图片保存到相册
  gal: ^2.3.2
  
  # 路径处理
  path_provider: ^2.1.5

  # 权限管理
  permission_handler: ^12.0.1

  # 加载动画
  flutter_spinkit: ^5.2.2

  # 日志
  logger: ^2.6.2
  # 高级日志工具
  talker: ^5.1.13
  talker_logger: ^5.1.13

  # 时间格式化
  intl: ^0.20.2

  # 弹窗
  flutter_easyloading: ^3.0.5

  # 徽章
  badges: ^3.1.2

  # 骨架屏
  shimmer: ^3.0.0

  # 评分星级
  flutter_rating_bar: ^4.0.1

  # 滑动面板
  sliding_up_panel: ^2.0.0+1

  # 分页视图
  infinite_scroll_pagination: ^5.1.1

  # 图片预览
  photo_view: ^0.15.0

  # 水平日历
  table_calendar: ^3.2.0

  # 剪切板
  clipboard: ^3.0.14

  # URL启动
  url_launcher: ^6.3.2
  flutter_toast_pro: ^2.1.1
  talker_dio_logger: ^5.1.13
  json_annotation: ^4.10.0
  flutter_screenutil: ^5.9.3
  signals: ^6.3.0

  # 视频播放
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  flutter_widget_from_html: ^0.17.1

  # 穿山甲广告SDK
  flutter_unionad: ^2.2.4

  # 微信SDK（分享、登录、支付）
  fluwx: ^5.7.5
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
